name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      ecr-registry:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for Kubernetes
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --region ${{ secrets.aws-region }} --name drec

      - name: Deploy to Kubernetes
        env:
          ECR_REGISTRY: ${{ secrets.ecr-registry }}
          ECR_REPOSITORY: drec-ui
          CONTAINER_NAME: drec-ui
          GITHUB_SHA: ${{ github.sha }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          kubectl -n ${ENVIRONMENT} set image deployment/${ECR_REPOSITORY} \
            ${CONTAINER_NAME}=$ECR_REGISTRY/$ECR_REPOSITORY:${ENVIRONMENT}-${GITHUB_SHA}
